
# output directory
out: "random-forest/TEST/HDL/"

# files
# TODO make list
metadata: "data/real-data-no-asvs.txt"
asv_biom: "data/real-feature-table.biom"
distance_matrix: "data/distance-matrix-hdl.tsv"

response_var: "HDL"
random_effect: "StudyID"
sample_ID: "StudyID.Timepoint"

# MERF arguments
iterations: "5"
n_estimators: "20"

# BorutaSHAP arguments
borutaSHAP_trials: "20"
borutaSHAP_percentile: "85"

# paths (relocate to path config file)
# TODO add dataset and create new folder
path_dim_pca: "01-DIM-PCA-metadata/"
path_dim_scnic: "01-DIM-SCNIC-biom/"

path_merged_data: "02-MERGED-DATA/"

path_rf_original: "04-SELECTED-FEATURES-original/"
path_rf_first: "04-SELECTED-FEATURES-first/"
path_rf_previous: "04-SELECTED-FEATURES-previous/"
path_rf_pairwise: "04-SELECTED-FEATURES-pairwise/"

