
# output directory
out: "random-forest/TEST/HDL/"


# files
# TODO make list

# TODO add original, first, previous and pairwise options

response_var: "HDL"
random_effect: "StudyID"
sample_id: "SampleID"


##### DIMENSIONALITY REDUCTION AND INTEGRATION #####
#rule dim_reduction_scnic and dim_reduction_pca can be combined
#rule integrate_datasets

#metadata: "data/hdl-test/real-data-no-asvs.txt"
#asv_biom: "data/hdl-test/real-feature-table.biom"

# Thttps://codebeautify.org/jsonviewer
#dataset_json: '{
#  "datasets": {
#    "dataset": [
#      {
#        "ds_name": "asvs",
#        "file_path": "data/hdl-test/real-feature-table.biom",
#        "dim_method": "scnic",
#        "param_dict": ""
#      },
#      {
#        "ds_name": "metadata",
#        "file_path": "data/hdl-test/real-data-no-asvs.txt",
#        "dim_method": "pca",
#        "param_dict": ""
#      }
#    ]
#  }
#}'


dataset_json: '{
  "datasets": {
      "metadata": {
      "ds_name": "metadata",
      "file_path": "data/hdl-test/real-data-no-asvs.txt",
      "dim_method": "pca",
      "param_dict": ""
    },
    "asvs": {
      "ds_name": "asvs",
      "file_path": "data/hdl-test/real-feature-table.biom",
      "dim_method": "scnic",
      "param_dict": ""
    }
  }
}'
#    "metadata2": {
#      "ds_name": "metadata2",
#      "file_path": "data/hdl-test/real-data-no-asvs-2.txt",
#      "dim_method": "pca",
#      "param_dict": ""
#    }


drop_rows: '{"SexualClassification": "Women"}'
constrain_rows: '{"Diet": "Agrarian"}'
drop_cols: '["Inflammation", "TotalCholesterol", "PCA", "HOMAIR"]'
constrain_cols: '[]'


#rule make_delta_datasets
distance_matrix: "data/hdl-test/distance-matrix-hdl.tsv"

# MOVE TO RF as a flag.
#rule visualize_datasets


##### Random Forest Arguments #####
#rule random_forest_deltas
#rule random_forest_original

# MERF arguments
iterations: "20"
n_estimators: "100"

# BorutaSHAP arguments
borutaSHAP_trials: "20"
borutaSHAP_percentile: "85"


# paths (relocate to path config file away from users)
# TODO add dataset and create new folder
path_dim_pca: "01-DIM-PCA/"
path_dim_scnic: "01-DIM-SCNIC/"

path_merged_data: "02-MERGED-DATA/"

path_rf_original: "04-SELECTED-FEATURES-original/"
path_rf_first: "04-SELECTED-FEATURES-first/"
path_rf_previous: "04-SELECTED-FEATURES-previous/"
path_rf_pairwise: "04-SELECTED-FEATURES-pairwise/"

