
### Constants for Demo
### ### ### ### ### ### ### ###
response_var: "HDL"
random_effect: "StudyID"
sample_id: "SampleID"

constrain_cols: '[]'

drop_rows: '{"SexualClassification": "Women"}'
constrain_rows: '{"Diet": "Agrarian"}'

# MERF arguments
iterations: "6"
n_estimators: "200"

# BorutaSHAP arguments
borutaSHAP_trials: "20"
borutaSHAP_percentile: "98"

# rule make_delta_datasets
distance_matrix: "data/hdl-test/distance-matrix-hdl.tsv"


out: "random-forest/TEST/HDL-Demo/"
report_name: "HDL-Demo.html"

#https://codebeautify.org/jsonviewer

# SCNIC param dict must have certain params

dataset_json: '{
  "datasets": {
    "metadata": {
      "file_path": "data/hdl-test/real-data-no-asvs-shuffled.txt",
      "dim_method": "pca",
      "param_dict": {}
    },
    "asvs": {
      "file_path": "data/hdl-test/real-feature-table.biom",
      "dim_method": "scnic",
      "param_dict": {
        "method": "spearman",
        "min_r": "0.35"
      }
    },
    "fake": {
      "file_path": "data/hdl-test/fake-demographics.txt",
      "dim_method": "None",
      "param_dict": {}
    }
  }
}'


#dataset_json: '{
#  "datasets": {
#    "metadata": {
#      "file_path": "data/hdl-test/real-data-no-asvs.txt",
#      "dim_method": "pca",
#      "param_dict": {}
#    },
#    "fake": {
#      "file_path": "data/hdl-test/fake-demographics.txt",
#      "dim_method": "None",
#      "param_dict": {}
#    }
#  }
#}'

# Demo3
drop_cols: '["Inflammation", "TotalCholesterol", "PCA", "HOMAIR"]'








#
## Demo3
#out: "random-forest/TEST/HDL-Demo4/"
#report_name: "HDL-Demo4.html"









# MOVE TO RF as a flag.
#rule visualize_datasets


##### Random Forest Arguments #####
#rule random_forest_deltas
#rule random_forest_original


